### ISSUE TITLE
Cinder throws errors if $HOME/.kube does not exist

### ISSUE THREAD

**Issue by brooksmtownsend** [criticalstack/crit#9]
`cinder create cluster` and `cinder export kubeconfig` will both fail if there is not already a `$HOME/.kube` directory created.

Output here:
```
❯ cinder create cluster
Creating cluster "cinder" ...
 🔥  Generating certificates
 🔥  Creating control-plane node
 🔥  Installing CNI
 🔥  Installing StorageClass
 🔥  Running post-up commands
<output elided>
2020/10/06 10:49:46 open /home/brooks/.kube/config.lock: no such file or directory

❯ cinder export kubeconfig
2020/10/06 10:54:56 open /home/brooks/.kube/config.lock: no such file or directory
```

Should be a simple fix to check for existence and create if not found to avoid the error

**Comment by ChrisRx** [comment]
https://github.com/criticalstack/crit/blob/master/pkg/kubeconfig/merge.go#L30

I'm thinking that the lockfile being initialized here should make sure the path it is given is created internally, so should be an easy fix everywhere by adding a MkdirAll to the lockfile constructor: 
 https://github.com/criticalstack/crit/blob/master/pkg/util/lockfile/lockfile.go#L13-L15
